spring.application.name=RMA

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_rma
spring.datasource.username=postgres
spring.datasource.password=igtsa120pm

# Auto-creates tables based on your Java code
# Change 'update' to 'create' for one run to reset the table properly
spring.jpa.hibernate.ddl-auto=update

# Ensure Hibernate uses snake_case for PostgreSQL columns
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Keep this to help with the reserved word issue
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true