spring.application.name=RMA

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_rma
spring.datasource.username=postgres
spring.datasource.password=igtsa120pm

# Auto-creates tables based on your Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true